//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Party.Services.PIPartyEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Master : Account
    {
        public string AccountName { get; set; }
    }
}
