//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Party.Services.PIPartyEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyRole
    {
        public int ID { get; set; }
        public System.Guid PartyId { get; set; }
        public int RoleTypeId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ThruDate { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual PartyRoleType PartyRoleType { get; set; }
    }
}
