//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Party.Services.PIPartyEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int ID { get; set; }
        public Nullable<System.Guid> PartyId { get; set; }
        public string CountryCode { get; set; }
        public string AreaCode { get; set; }
        public string PhoneLine { get; set; }
        public int PurposeTypeID { get; set; }
        public string PhoneExchange { get; set; }
    
        public virtual Party Party { get; set; }
        public virtual PhonePurpose PhonePurpose { get; set; }
    }
}
