//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Party.Services.PIPartyEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PIPartyEF : DbContext
    {
        public PIPartyEF()
            : base("name=PIPartyEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressPurpose> AddressPurposes { get; set; }
        public virtual DbSet<EmailAddress> EmailAddresses { get; set; }
        public virtual DbSet<EmailPurpose> EmailPurposes { get; set; }
        public virtual DbSet<Party> Parties { get; set; }
        public virtual DbSet<PhonePurpose> PhonePurposes { get; set; }
        public virtual DbSet<PartyRole> PartyRoles { get; set; }
        public virtual DbSet<PartyRoleType> PartyRoleTypes { get; set; }
        public virtual DbSet<ModuleSchemaSetting> ModuleSchemaSettings { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<Account_SECRM> Account_SECRM { get; set; }
    }
}
