//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PI.Party.Services.PIPartyEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> RegistrationTokenId { get; set; }
        public Nullable<System.DateTime> DateTimeCreated { get; set; }
        public Nullable<System.Guid> PartyId { get; set; }
        public Nullable<System.DateTime> LoginCreatedDate { get; set; }
        public Nullable<System.DateTime> DateTimeTokenSent { get; set; }
        public Nullable<int> TokenCount { get; set; }
        public bool RegistrationDenied { get; set; }
        public string ReasonForDenial { get; set; }
    
        public virtual Party Party { get; set; }
    }
}
